name: budget_buddy
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.1.2 <4.0.0"

dependencies:
    firebase_auth: ^4.12.1
    firebase_core: ^2.21.0
    flutter:
        sdk: flutter
    google_fonts: ^6.1.0
    shared_preferences: ^2.2.2
    percent_indicator: ^4.0.1
    intl:

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
    fonts:
        - family: Montserrat
          fonts:
              - asset: fonts/Montserrat-Regular.ttf
                weight: 400
              - asset: fonts/Montserrat-Bold.ttf
                weight: 700
              - asset: fonts/Montserrat-Medium.ttf
                weight: 500
              - asset: fonts/Montserrat-SemiBold.ttf
                weight: 600
